### ISSUE TITLE
Is possible to create a NuGet package?

### ISSUE THREAD

**Issue by iluvadev** [PRCV1/pocketbase-csharp-sdk#13]
Hi, 
I'm trying to create a new Nuget package for my project [PocketBaseClient-csharp](https://github.com/iluvadev/PocketBaseClient-csharp), but as it uses pocketbase-csharp-sdk I found some problems resolving dependences: NU1101: Unable to find package
I could include the sdk dll in my package, but I think that the best solution would be a reference to the sdk nuget package.

Is possible to have a Nuget package of the sdk? (for testing purposes)
Tanks!

**Comment by PRCV1** [comment]
Hey,

I was planning to do that as well, I have already created an account at nuget.com. I still have to deal with how to create and upload such a package. I'll try that on a test basis this weekend.

**Comment by iluvadev** [comment]
Ok!
Is simple, maybe the first time is a litle confusing, but easy:
In VS, at the project properties:
- Application -> Packaging: Mark the "publishing" checkbox
- Review Package options (also the Package Version!)

Also in VS, you can configure the "Publish" option to publish in a folder.
Then, you can "Publish", and VS generates the nuget package automatically

In Nuget webpage -> "Upload Package" and select the file ".nupkg" in your "Publish" folder 

And thats all! ;)

**Comment by PRCV1** [comment]
Hi,

I just uploaded the package:
https://www.nuget.org/packages/pocketbase-csharp-sdk/

Let me know if everything is working as expected, thanks.

**Comment by iluvadev** [comment]
Thanks! Is perfect!
I tested the nuget Package in a project and as reference in other nuget Package: It works!

Thanks :)
